### ISSUE TITLE
Asked to pass Tests, but is a lecture

### ISSUE THREAD

**Issue by edmundo096** [learn-co-curriculum/moving-things-with-javascript#12]
On https://learn.co/tracks/full-stack-community-bootcamp/javascript-foundations/jquery/moving-things-with-javascript the lab is treated as a lecture.
We have to fork it, then we are able to manually create a test it to make it pass with `learn`, and then `learn submit` it.

**Comment by gj** [comment]
It's appearing as a Readme now. Thanks @edmundo096 !
