### ISSUE TITLE
Error in test suite

### ISSUE THREAD

**Issue by cassaram09** [learn-co-curriculum/moving-things-with-javascript#16]
```
it('runs', () => {
    expect(true).to.be.true
})
```
The only test in this lab throws an error when the test suite is run. The correct syntax for the test is apparently `expect(true).toBe.true`.

**Comment by ktravers** [comment]
should be fixed by #18

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
