### ISSUE TITLE
Moving Things With Javascript to.be.true Error.

### ISSUE THREAD

**Issue by chanfe** [learn-co-curriculum/moving-things-with-javascript#20]
On the index-test.js there is an TypeError on line 16, it cannot fine "be" in this scenario.  

describe('index', () => {
  jsdom({
    src: fs.readFileSync(path.resolve(__dirname, '..', 'index.js'), 'utf-8')
  })
  it('runs', () => {
    ***expect(true).to.be.true***
  })
})

One way I found it to work is:

describe('index', () => {
  jsdom({
    src: fs.readFileSync(path.resolve(__dirname, '..', 'index.js'), 'utf-8')
  })
  it('runs', () => {
    ***expect(true).isTrue***
  })
})

I presume that this test just make sure it runs correctly hence true === true.  
Or that it will always be true so that the student can run the test correctly and submit it.

**Comment by chanfe** [comment]
also 
***expect(true).toBe.true***
works as well!
courtesy from #cassaram09

**Comment by ktravers** [comment]
should be fixed by #18

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
