### ISSUE TITLE
test is written incorrectly

### ISSUE THREAD

**Issue by magic8baller** [learn-co-curriculum/moving-things-with-javascript#21]
The test/index-test.js file test is written as:

  it('runs', () => {
    expect(true).to.be.true
  })

BUT should be written as:

  it('runs', () => {
    expect(true).toBe.true
  })

**Comment by justinddaniel** [comment]
Affirmative on the incorrect test and correct solution provided above.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
