### ISSUE TITLE
toBe (or not) to.be

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/moving-things-with-javascript#22]
1) index runs:
     TypeError: Cannot read property 'be' of undefined
      at Context.it (test/index-test.js:16:20)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
