### ISSUE TITLE
Needs tests

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/moving-things-with-javascript#3]
I don't know if this is a new deployment strategy issue or not, but the student repo has a "test" that is not present here.

[issue from student repo](https://github.com/learn-co-students/moving-things-with-javascript-js-intro-000/issues/2)

**Comment by AnnJohn** [comment]
lab isn't tested and is meant to be more of a codealong as stated towards the end of the lesson. can could you link to the student repo that has tests in it?

**Comment by bhollan** [comment]
The link above is for an issue from [the student repo](https://github.com/learn-co-students/moving-things-with-javascript-js-intro-000).

**Comment by bhollan** [comment]
The "non-tests" that were there weren't even passing.  I [made a PR](https://github.com/learn-co-students/moving-things-with-javascript-js-intro-000/pull/5) to where it at least passes for now.

**Comment by AnnJohn** [comment]
changed this to a Readme and should show up without tests on the student side
