### ISSUE TITLE
Lab isn't rendering as a ReadMe

### ISSUE THREAD

**Issue by TheLucasMoore** [learn-co-curriculum/moving-things-with-javascript#8]
I see the closed issues already on this repo about the testing issues. The resolution was to switch the lab to being a ReadMe. 

When I access this lab on Learn.co, it renders as a lab with tests, which still fail. 

Two students brought this to my attention as they ran into the same errors when trying to run the tests on Learn.co within the `Intro to JavaScript` track.

**Comment by TheLucasMoore** [comment]
@aturkewi

**Comment by aturkewi** [comment]
@TheLucasMoore what batch are they one? I'm on the js-intro-000 batch and this is showing up as a readme. 

![screen shot 2016-09-19 at 3 51 44 pm](https://cloud.githubusercontent.com/assets/13033515/18646757/02bb7896-7e81-11e6-87fd-8e39b8f49e5c.png)

**Comment by aturkewi** [comment]
Update: I'm an idiot. Screenshot above is from a different lesson. 

Fixed:
![screen shot 2016-09-19 at 4 00 23 pm](https://cloud.githubusercontent.com/assets/13033515/18647038/333c8c20-7e82-11e6-8e2d-ce2c58cd3118.png)
